// Static fallback content — override via Directus (slug = key name)

export const products = {
  axp: {
    slug: 'product-axp',
    eyebrow: 'Agent Experience Platform',
    hero_title: 'Serve every AI agent\nthe perfect content.',
    hero_desc: 'AXP detects AI crawlers at the network edge and delivers token-efficient, structured responses — without changing a single line of your codebase.',
    badge: '−98.99% token reduction',
    steps: [
      { num: '01', title: 'Agent detected at edge', desc: 'ChatGPT, Perplexity, Claude, Bing AI and 60+ other agents are identified in <5ms.' },
      { num: '02', title: 'Content transformed', desc: 'AXP strips JS, nav, and decorative HTML — serving clean, structured facts.' },
      { num: '03', title: 'Human view preserved', desc: 'Your visitors get the full experience. Agents get their own optimized version.' },
      { num: '04', title: 'Citations tracked', desc: 'Every agent visit is logged. See which pages earn citations and which get ignored.' },
    ],
    features: [
      { icon: '⚡', title: 'Edge detection', desc: 'Identify 60+ AI agents at the CDN level with zero app-layer overhead.',
        body: ['AXP maintains a continuously updated fingerprint database of 60+ AI crawlers — from GPT-4o\'s OAI-SearchBot to Perplexity\'s PerplexityBot and Claude\'s ClaudeBot. Detection happens at the CDN layer in under 5ms, before any server-side code runs.', 'Unlike user-agent string matching alone, AXP cross-references IP ranges, request headers, and crawl behavior patterns — making it resilient to agent spoofing and new crawler variants.'],
        points: ['60+ AI agents in the detection database', 'Sub-5ms identification at the edge', 'Updates within 24h of new agent releases', 'No changes to your app or codebase'] },
      { icon: '🗜', title: 'Token compression', desc: 'Reduce page weight 90–99% for LLMs. More context, fewer tokens spent.',
        body: ['A standard marketing page runs 50,000–150,000 tokens when naively fed to an LLM. AXP strips JavaScript bundles, navigation, footers, decorative elements, and inline styles — delivering a clean, semantic version that\'s typically 500–2,000 tokens.', 'This isn\'t simple HTML stripping. AXP uses a semantic extraction model trained on 10M pages to understand which content carries factual signal — and preserves it in full while discarding the rest.'],
        points: ['90–99% average token reduction', 'Semantic extraction preserves factual content', 'Configurable compression levels per page type', 'No degradation in citation accuracy'] },
      { icon: '📄', title: 'Structured content', desc: 'Auto-generate semantic HTML, JSON-LD, and citation-ready fact blocks.',
        body: ['AI models cite structured facts more reliably than prose. AXP automatically generates JSON-LD markup for your product, organization, FAQ, and article entities — without requiring manual schema implementation.', 'Beyond schema, AXP injects "fact blocks" — concise, citation-optimized summaries of key claims on each page. These are invisible to human visitors but appear prominently in the agent-facing version of your content.'],
        points: ['Auto-generated JSON-LD for 12 schema types', 'AI-facing fact blocks on every page', 'Semantic heading restructuring for context clarity', 'Citation-optimized meta descriptions'] },
      { icon: '🔬', title: 'Agent A/B testing', desc: 'Serve multiple content variants to different agents and measure citation lift.',
        body: ['AXP lets you define multiple content variants per page and route different AI agents to each. Run a controlled experiment — serve ChatGPT a fact-block-heavy version while Perplexity gets structured Q&A — and measure which earns more citations within each model.', 'Unlike traditional A/B testing, agent experiments give fast signal: you can detect citation rate differences within 48–72 hours at moderate traffic volumes, without waiting for statistical significance across human conversion funnels.'],
        points: ['Up to 4 simultaneous content variants per page', 'Per-model routing and traffic splitting', 'Citation lift tracking per variant', 'Auto-promotes winning variant after significance'] },
      { icon: '📡', title: 'Live agent logs', desc: 'Real-time feed of every agent crawl with user-agent, content served, and response time.',
        body: ['Every AI agent visit to your site is captured in real time: which model, which page, what content was served, how many tokens, and the full HTTP response time. The live log streams into your Enigma dashboard within 2 seconds of each crawl.', 'Beyond raw logging, AXP clusters crawl sessions — so you can see when GPT-4o ran a multi-page research crawl starting from your homepage, rather than just individual pageview events.'],
        points: ['Real-time log stream with <2s latency', 'Full session clustering by agent and crawl intent', 'Content snapshot: exactly what each agent received', 'Exportable to BigQuery, Snowflake, or S3'] },
      { icon: '💾', title: 'Smart caching', desc: 'Agent-optimized content is cached separately. Zero latency for returning crawlers.',
        body: ['Agent-optimized responses are cached at the CDN edge with a separate cache namespace from your human-facing pages. When the same crawler returns within the cache TTL, it gets a sub-millisecond response — no compute cost, no origin hit.', 'Cache invalidation is intelligent: a content update on your CMS triggers selective recompilation of affected agent pages rather than a full cache flush, keeping your CDN hit rate consistently above 95%.'],
        points: ['Dedicated agent cache namespace at the CDN', '<1ms cached response time for returning crawlers', 'Selective invalidation on content updates', '>95% cache hit rate in production'] },
    ],
    stats: [{ value: '60+', label: 'AI agents detected' }, { value: '<5ms', label: 'Detection overhead' }, { value: '99%', label: 'Token reduction' }],
    cta_title: 'Ready to serve AI agents perfectly?',
    cta_desc: 'Deploy AXP in minutes — no code changes needed.',
  },
  'agent-traffic': {
    slug: 'product-agent-traffic',
    eyebrow: 'Agent Traffic',
    hero_title: 'See every AI bot\nthat visits your site.',
    hero_desc: 'Agent Traffic reveals which AI systems are crawling your pages, how often, and what content they consume — giving you complete visibility into your AI audience.',
    badge: '1.8M+ agent visits tracked weekly',
    steps: [
      { num: '01', title: 'Passive monitoring', desc: 'No SDK, no script tags. Agent Traffic reads your server logs or CDN events.' },
      { num: '02', title: 'Agent fingerprinting', desc: 'Each visit is matched against our database of 60+ known AI crawlers.' },
      { num: '03', title: 'Content mapping', desc: 'See which pages, sections, and structured data get consumed.' },
      { num: '04', title: 'Trend alerts', desc: 'Get notified when a new AI system starts crawling or traffic spikes unexpectedly.' },
    ],
    features: [
      { icon: '📊', title: 'Real-time dashboard', desc: 'Live feed of agent visits — model, page, timestamp, content consumed.',
        body: ['The Agent Traffic dashboard streams every AI crawl event as it happens. You can filter by model (ChatGPT, Perplexity, Claude, Gemini), page section, or date range — giving you a live view of which AI systems are actively researching your site right now.', 'Each row in the live feed shows the agent fingerprint, the exact URL crawled, the content type served, estimated tokens consumed, and response time. Clicking any row expands a full crawl trace.'],
        points: ['Live feed with <2s event latency', 'Filter by model, page, content type, or date', 'Full crawl trace on every event', 'Mobile-ready dashboard with push alerts'] },
      { icon: '📈', title: 'Historical trends', desc: 'Track how AI traffic to your site evolves week over week.',
        body: ['Agent Traffic stores the complete crawl history for your site — so you can see not just today\'s numbers but how your AI audience has grown (or shrunk) over the past 12 months. Track weekly active agents, visits per model, and total pages consumed per crawl session.', 'Trend charts overlay key events — a new content publish, a competitor launch, a model update — so you can correlate external events with changes in your AI traffic patterns.'],
        points: ['12 months of crawl history included', 'Week-over-week and month-over-month comparisons', 'Event annotations on trend charts', 'Custom date range comparisons'] },
      { icon: '🔍', title: 'Page-level insights', desc: 'Discover which pages attract the most AI attention and why.',
        body: ['Not all pages are equal in the eyes of AI. Agent Traffic breaks down crawl volume by URL, showing you the pages that get the most attention from AI systems — and those that get none. This often reveals surprising gaps: a blog post from two years ago that\'s now being heavily cited, or a high-traffic landing page that agents consistently skip.', 'For each high-traffic page, you can see which agents visit most, how much of the page they consume, and how this has changed over time.'],
        points: ['Per-URL crawl volume and trend data', 'Content consumption depth by page', 'AI model breakdown per page', 'Gap identification for uncrawled high-value content'] },
      { icon: '🔔', title: 'Anomaly detection', desc: 'Automatic alerts for unusual crawl patterns or new agent types.',
        body: ['Agent Traffic\'s anomaly engine monitors your crawl patterns and alerts you when something unusual happens: a 10× spike in Perplexity visits, a new unrecognized agent appearing in your logs, or a sudden drop-off in ChatGPT crawls that could indicate a demotion.', 'Alerts are delivered via Slack, email, or webhook within 5 minutes of detection. Each alert includes context — the historical baseline, the deviation magnitude, and possible explanations.'],
        points: ['Spike and drop-off detection on all agent types', 'New agent fingerprint alerts', 'Slack, email, and webhook delivery', 'Alert history with resolution tracking'] },
      { icon: '🏁', title: 'Competitor comparison', desc: 'Benchmark your AI traffic vs. similar sites in your category.',
        body: ['Agent Traffic includes an anonymized industry benchmark dataset — so you can see how your AI crawl volume, agent diversity, and page coverage compare to similar sites. If your category peers are getting 3× more Perplexity visits, that\'s a signal worth acting on.', 'Competitor comparison is available for direct competitors you specify — with permission-based data sharing or our aggregated benchmark pools for your vertical.'],
        points: ['Industry benchmark data for your vertical', 'Direct competitor comparison with consent', 'Per-model share of voice vs. competitors', 'Monthly benchmarking reports'] },
      { icon: '🔗', title: 'Export & API', desc: 'Push agent traffic data into your data warehouse or BI tools.',
        body: ['All Agent Traffic data is available via a REST API and webhook stream. Push your crawl events into BigQuery, Snowflake, Redshift, or any BI tool that accepts JSON — so you can join AI traffic data with your conversion and revenue metrics in a single view.', 'Pre-built connectors are available for Looker, Tableau, and Google Data Studio. For custom pipelines, the API provides cursor-based pagination for bulk historical exports.'],
        points: ['REST API with full crawl event access', 'Webhook stream for real-time data pipelines', 'Pre-built connectors for major BI tools', 'Historical bulk export with cursor pagination'] },
    ],
    stats: [{ value: '1.8M+', label: 'Agent visits weekly' }, { value: '60+', label: 'Agent types identified' }, { value: 'Real-time', label: 'Data latency' }],
    cta_title: 'Know exactly who\'s crawling you.',
    cta_desc: 'Connect in minutes via log forwarding or our CDN plugin.',
  },
  'site-maps': {
    slug: 'product-site-maps',
    eyebrow: 'Site Maps',
    hero_title: 'Map exactly how\nAI consumes your site.',
    hero_desc: 'Site Maps renders your site through the eyes of every major AI model — showing which pages get read, which get skipped, and what content ends up in context windows.',
    badge: 'Full crawl simulation in 30s',
    steps: [
      { num: '01', title: 'Crawl simulation', desc: 'We simulate how GPT, Claude, Perplexity and others actually process your pages.' },
      { num: '02', title: 'Content visibility score', desc: 'Every page gets scored: how much of it reaches an AI context window?' },
      { num: '03', title: 'Gap identification', desc: 'Find pages that are technically crawlable but effectively invisible to AI.' },
      { num: '04', title: 'Fix recommendations', desc: 'Actionable fixes: semantic structure, token density, internal linking.' },
    ],
    features: [
      { icon: '🗺️', title: 'Visual site map', desc: 'Interactive map of your entire site from the AI perspective.',
        body: ['Site Maps renders your site structure as a navigable graph — showing every URL, how they link together, and which ones AI agents actually visit. Nodes are sized by crawl frequency and colored by visibility score, so you can instantly see your site\'s AI footprint at a glance.', 'Zoom in to any section to see the page-level detail: content score, last crawl date, schema coverage, and linked pages. Click any node to open the full page analysis view.'],
        points: ['Full site graph with 10,000+ URL support', 'Crawl frequency and visibility scoring per node', 'Internal link coverage visualization', 'Export as PNG, SVG, or structured JSON'] },
      { icon: '👁️', title: 'Content visibility scores', desc: 'Page-by-page scoring of AI readability and context coverage.',
        body: ['Every page on your site gets a 0–100 visibility score based on four factors: token efficiency (how much useful content per token), semantic structure (heading hierarchy, fact density), schema coverage (JSON-LD completeness), and citation history (whether AI has cited this page before).', 'Scores above 80 are considered "citation-ready." Pages between 40–79 have clear improvement opportunities. Pages below 40 are effectively invisible to AI — despite being indexed by Google.'],
        points: ['0–100 score with four component factors', 'Actionable breakdown for each score component', 'Historical score tracking over time', 'Batch fix recommendations for low-scoring pages'] },
      { icon: '🌡️', title: 'Token heatmaps', desc: 'See which parts of each page make it into an AI\'s context window.',
        body: ['When an AI agent processes your page, it doesn\'t read everything — it prioritizes. Token heatmaps overlay a gradient on your rendered page showing exactly which sections get high, medium, or low weight in the AI\'s context window, based on how our models simulate six major AI systems.', 'Green sections are almost always included; yellow sections make it in when the context budget allows; red sections are routinely truncated or ignored. This visualization makes content prioritization decisions obvious.'],
        points: ['Simulated for GPT-4o, Claude, Perplexity, and Gemini', 'Section-level and paragraph-level granularity', 'Before/after comparison after content changes', 'Exportable annotation for editorial teams'] },
      { icon: '🔀', title: 'Crawl path analysis', desc: 'Understand the order in which agents process your site structure.',
        body: ['AI agents don\'t crawl randomly — they follow link patterns, sitemap structures, and internal anchor text signals. Crawl path analysis reconstructs the sequence in which agents traverse your site and identifies which pages act as entry points vs. dead ends.', 'If your most important product pages are only reachable after 4 hops from the homepage, they\'re at risk of being missed in shallower crawl sessions. Crawl path analysis flags these structural gaps and shows you how to fix the internal link structure.'],
        points: ['Multi-hop crawl path reconstruction', 'Entry point and dead-end identification', 'Depth-from-root scoring for all pages', 'Internal link improvement recommendations'] },
      { icon: '🧩', title: 'Schema coverage', desc: 'Audit structured data coverage across your entire site.',
        body: ['Structured data is one of the strongest signals for AI citation — but most sites have incomplete, inconsistent, or outright broken schema markup. Site Maps audits every page for 12 schema types (Product, Organization, FAQ, Article, and more) and flags missing, malformed, or conflicting markup.', 'The schema coverage report shows your overall coverage percentage, pages with critical gaps, and a priority list of schema additions that would have the highest impact on citation rates based on your content type.'],
        points: ['Audit of 12 JSON-LD schema types', 'Malformed and conflicting markup detection', 'Coverage percentage by schema type', 'One-click schema snippet generation'] },
      { icon: '🏆', title: 'Competitor crawl maps', desc: 'Compare how AI processes your site vs. top competitors.',
        body: ['Site Maps can run the same crawl simulation against your competitors\' sites — giving you a side-by-side view of how AI processes each site. Compare visibility scores, page coverage, schema implementation, and internal link structure across up to 5 competitor domains.', 'Competitor crawl maps often reveal surprising asymmetries: a competitor with less traffic but much higher AI visibility because they\'ve structured their content for machine reading. These gaps become your highest-priority optimization targets.'],
        points: ['Crawl simulation for up to 5 competitors', 'Side-by-side visibility score comparison', 'Schema and structure gap analysis', 'Updated on your chosen cadence (weekly to monthly)'] },
    ],
    stats: [{ value: '30s', label: 'Full crawl simulation' }, { value: '100%', label: 'Page coverage' }, { value: '6', label: 'Models simulated' }],
    cta_title: 'See your site the way AI does.',
    cta_desc: 'Run your first crawl simulation free — no credit card needed.',
  },
  monitoring: {
    slug: 'product-monitoring',
    eyebrow: 'Monitoring & Citations',
    hero_title: 'Know exactly when\nAI mentions you.',
    hero_desc: 'Monitor thousands of prompts across ChatGPT, Perplexity, Claude, and Gemini — and get alerted the moment your brand appears, disappears, or gets outranked.',
    badge: '8M+ citations tracked weekly',
    steps: [
      { num: '01', title: 'Set up prompts', desc: 'Define the queries that matter to your buyers. We run them across all major AI models.' },
      { num: '02', title: 'Track responses', desc: 'Every AI answer is captured, parsed, and analyzed for brand mentions and citations.' },
      { num: '03', title: 'Competitive benchmarking', desc: 'See how your presence compares to competitors for each prompt category.' },
      { num: '04', title: 'Alert & optimize', desc: 'Get notified of drops. Our recommendations show you what to fix.' },
    ],
    features: [
      { icon: '🤖', title: 'Multi-model monitoring', desc: 'Track mentions across ChatGPT, Perplexity, Claude, Gemini, Bing AI and more.',
        body: ['Enigma runs your tracked prompts across five major AI systems every day: ChatGPT (GPT-4o), Perplexity, Claude (Sonnet), Gemini (1.5 Pro), and Bing AI. Each model gets its own response captured, parsed, and analyzed — because what ChatGPT says about your brand and what Perplexity says can be dramatically different.', 'Enterprise plans can extend monitoring to additional models including open-source LLMs and emerging regional AI systems as they gain market share.'],
        points: ['5 AI models monitored daily by default', 'Per-model presence score and trend', 'Response capture and full text archive', 'Enterprise: custom and emerging model support'] },
      { icon: '🔖', title: 'Citation tracking', desc: 'See exactly which sources AI cites when it mentions your category.',
        body: ['When an AI model mentions your brand or product, it often cites a specific source — a blog post, a review site, a press mention. Citation tracking captures every source URL that appears alongside your brand in AI responses, showing you which content assets are driving your AI presence and which third-party sites carry the most weight.', 'You can see the full citation chain: which prompts produce mentions, which mentions include citations, and which source URLs are cited most. This shows you exactly where to invest in content — and which publisher relationships matter most for AI.'],
        points: ['Full source URL capture per AI response', 'Citation frequency ranking by source domain', 'First-party vs. third-party citation breakdown', 'Citation trend tracking over time'] },
      { icon: '💬', title: 'Sentiment analysis', desc: 'Understand how AI describes your brand — positive, neutral, or negative.',
        body: ['It\'s not enough to know whether AI mentions you — you need to know what it says. Sentiment analysis classifies every AI mention of your brand as positive, neutral, or negative, and extracts the specific language used to describe you: "industry-leading," "expensive but reliable," or "complex setup."', 'Over time, you can track whether your AI reputation is improving as you publish new content, earn better reviews, or address known weaknesses. Sentiment shifts often precede changes in citation frequency by 2–4 weeks.'],
        points: ['Positive / neutral / negative classification per mention', 'Key descriptor extraction and tracking', 'Sentiment trend with 90-day history', 'Competitor sentiment comparison'] },
      { icon: '🎯', title: 'Competitive intelligence', desc: 'Know which competitors are mentioned more often and why.',
        body: ['For every prompt you monitor, Enigma tracks not just your mentions but all competitor mentions in the same AI response. You can see your share of voice — what percentage of relevant AI answers include your brand vs. each competitor — and how that\'s changed over the past 90 days.', 'Competitive intelligence also shows you which content assets your competitors are getting cited for, so you can identify the specific pages or topics where they\'ve earned AI authority that you haven\'t.'],
        points: ['Share of voice vs. up to 10 competitors', 'Competitor citation source analysis', 'Prompt-level win/loss breakdown', 'Monthly competitive summary report'] },
      { icon: '📈', title: 'Historical trends', desc: 'Track your AI presence over time and measure the impact of content changes.',
        body: ['Every monitoring metric — mention rate, citation count, sentiment score, share of voice — is stored historically so you can track your AI presence trajectory over the full lifetime of your account. Correlate presence changes with content publishes, product launches, or PR events to understand what\'s actually moving the needle.', 'Historical trends also power our ROI attribution model: by tracking which content changes precede citation increases, Insights can estimate the pipeline impact of your GEO investment.'],
        points: ['Full metric history from account creation', 'Event annotation for content publishes and campaigns', 'Attribution modeling for content ROI', 'Year-over-year comparison views'] },
      { icon: '🔔', title: 'Custom alerts', desc: 'Slack and email alerts when your brand presence drops or spikes.',
        body: ['Set threshold-based alerts for any monitoring metric: get notified when your mention rate drops below 40%, when a competitor\'s share of voice spikes above yours, or when a new source starts citing your brand for the first time. Alerts fire within 5 minutes of detection.', 'Alert conditions are fully configurable — you can set different thresholds per model, per prompt category, or per competitor. Alerts include full context: the prompt, the AI response, and the metric change — so your team can act immediately.'],
        points: ['Threshold alerts on all monitoring metrics', 'Per-model and per-competitor alert conditions', '<5 minute detection and delivery', 'Slack, email, and webhook channels'] },
    ],
    stats: [{ value: '8M+', label: 'Citations tracked weekly' }, { value: '4', label: 'Major AI models' }, { value: 'Daily', label: 'Prompt refresh rate' }],
    cta_title: 'Never miss an AI mention again.',
    cta_desc: 'Start monitoring your brand across all AI search engines today.',
  },
  insights: {
    slug: 'product-insights',
    eyebrow: 'Insights',
    hero_title: 'Turn AI data\ninto growth actions.',
    hero_desc: 'Insights synthesizes your monitoring data, citation patterns, and competitive landscape into a prioritized action plan — so your team always knows what to do next.',
    badge: 'Prioritized recommendations weekly',
    steps: [
      { num: '01', title: 'Data aggregation', desc: 'All your AXP, monitoring, and traffic data is synthesized automatically.' },
      { num: '02', title: 'Gap analysis', desc: 'Our AI identifies where you\'re underperforming vs. your potential.' },
      { num: '03', title: 'Action scoring', desc: 'Every recommendation is scored by expected citation lift and effort required.' },
      { num: '04', title: 'Progress tracking', desc: 'Measure how each action improves your AI presence over time.' },
    ],
    features: [
      { icon: '📰', title: 'Weekly AI briefing', desc: 'Automated digest of your AI presence, wins, and opportunities.',
        body: ['Every Monday morning, Insights sends your team a structured briefing covering the past week\'s AI presence data: citation count, mention rate by model, top-cited pages, competitor movement, and the highest-priority actions for the week ahead.', 'Briefings are role-specific: executives get the executive summary (presence trend, revenue impact); content teams get the specific pages and topics to work on; engineering gets the technical AXP action items. No more digging through dashboards to find what matters.'],
        points: ['Automated weekly briefing every Monday 9am', 'Role-specific views for exec, content, and engineering', 'Includes competitive movement and alerts from the week', 'Delivered via email with deep links to the dashboard'] },
      { icon: '🔍', title: 'Content gap finder', desc: 'Discover topics where you\'re missing from AI answers entirely.',
        body: ['Content gap finder analyzes 10,000+ prompts related to your industry and identifies the topics where your competitors appear in AI answers but you don\'t. These aren\'t just keyword gaps — they\'re specific questions buyers are asking AI that your site doesn\'t answer.', 'Each identified gap includes: the prompt category, which competitors are filling it, the estimated monthly query volume, and a suggested content brief for addressing it. Gaps are prioritized by commercial intent and citation difficulty.'],
        points: ['10,000+ prompt gap analysis per vertical', 'Competitor-filling detection per topic', 'Commercial intent scoring per gap', 'AI-generated content briefs for each gap'] },
      { icon: '⚡', title: 'Quick wins queue', desc: 'Low-effort, high-impact actions ranked by expected citation lift.',
        body: ['The quick wins queue surfaces the specific, concrete actions your team can take this week to improve AI presence — ranked by the ratio of expected citation lift to implementation effort. A typical queue includes: add FAQ schema to a pricing page (2 hours, +18% citation lift), restructure a product comparison page (4 hours, +12% lift), add a fact block to a high-traffic blog post (1 hour, +9% lift).', 'Each action includes a specific implementation guide, the pages affected, the expected timeline to see impact, and success metrics to verify the change worked.'],
        points: ['Effort-weighted citation lift scoring', 'Specific implementation guide per action', 'Expected time-to-impact estimate', 'Automatic success detection after implementation'] },
      { icon: '💰', title: 'ROI dashboard', desc: 'Track how AI visibility translates to pipeline and revenue.',
        body: ['Connecting AI visibility to revenue has been the hardest part of justifying GEO investment. The ROI dashboard solves this by tracking the path from AI citation → website visit → pipeline opportunity → closed revenue — using UTM parameters and CRM integration to close the attribution loop.', 'Even without CRM integration, the dashboard models the revenue impact using your conversion rates and average deal values, giving you a defensible estimate of GEO\'s contribution to pipeline — ready for your quarterly business review.'],
        points: ['Full attribution: citation → visit → pipeline → revenue', 'CRM integration (Salesforce, HubSpot)', 'Revenue model for orgs without CRM integration', 'Board-ready ROI summary with one click'] },
      { icon: '👥', title: 'Team collaboration', desc: 'Assign actions, set owners, and track completion across your team.',
        body: ['Every recommended action in Insights can be assigned to a team member with a due date, priority level, and success criteria. Owners get notified via Slack or email, and the dashboard tracks completion status — so nothing falls through the cracks between the insight and the implementation.', 'Team leads can see the full action queue across all team members: what\'s in progress, what\'s overdue, what\'s been completed, and how completed actions have moved the presence metrics. Think of it as a Jira for your GEO work.'],
        points: ['Action assignment with due dates and owners', 'Slack notifications for assigned actions', 'Completion tracking with impact verification', 'Team-level progress view for managers'] },
      { icon: '🔌', title: 'Integrations', desc: 'Push insights into Notion, Linear, Jira, or your CMS.',
        body: ['Insights integrates with the tools your team already uses. Send recommended actions directly to Linear issues, Jira tickets, or Notion pages with full context pre-filled. When an action is marked complete in your project management tool, Enigma automatically verifies the impact and updates the metric.', 'For content teams, the CMS integration (Webflow, Contentful, WordPress) can push fact-block recommendations directly into your publishing workflow — so writers see the AI optimization suggestions alongside the content editor.'],
        points: ['Native integrations: Linear, Jira, Notion, Asana', 'CMS plugins: Webflow, Contentful, WordPress', 'Two-way sync: completion status flows back to Enigma', 'Zapier/Make connector for custom workflows'] },
    ],
    stats: [{ value: 'Weekly', label: 'Action briefings' }, { value: '3×', label: 'Avg. citation lift' }, { value: '90 days', label: 'Avg. to first results' }],
    cta_title: 'Start acting on AI data.',
    cta_desc: 'Insights is included in all Enigma plans.',
  },
};

export const solutions = {
  'b2b-saas': {
    slug: 'solution-b2b-saas',
    eyebrow: 'For B2B SaaS',
    hero_title: 'Win deals decided\nin AI conversations.',
    hero_desc: 'B2B buyers now ask AI before they ask Google. Enigma makes sure your SaaS product is the one that gets recommended — for every relevant use case, across every AI model.',
    pain_points: [
      { title: 'Buyers research in AI', desc: '"What\'s the best CRM for a 50-person sales team?" — If you\'re not the answer, you lose the deal before your SDR even reaches out.' },
      { title: 'Competitors are already there', desc: 'While you optimize for Google, your competitors are investing in AI presence. The window to move first is closing.' },
      { title: 'No visibility into AI traffic', desc: 'You can\'t see which AI systems visit your site, what they consume, or whether your content earns citations.' },
    ],
    benefits: [
      { icon: '🎯', title: 'Own high-intent AI queries', desc: 'Identify the prompts your ideal buyers ask AI and engineer your site to be the cited answer.' },
      { icon: '🔍', title: 'Track competitor mentions', desc: 'Know every time a competitor gets recommended instead of you — and see exactly why.' },
      { icon: '⚡', title: 'Serve AI the facts it needs', desc: 'AXP serves structured, token-efficient content to AI crawlers. More citations, fewer tokens wasted.' },
    ],
    quote: '"More of our pipeline now comes from AI-influenced research than Google. Enigma was the fastest way to own that channel."',
    quote_author: 'Jordan Duarte',
    quote_role: 'Sr. Director of Web Strategy, Notion',
    stat: '412%',
    stat_label: 'increase in brand presence for non-branded prompts',
    cta_title: 'Win the AI search channel.',
    cta_desc: 'Book a demo to see how Enigma works for B2B SaaS.',
  },
  ecommerce: {
    slug: 'solution-ecommerce',
    eyebrow: 'For E-commerce',
    hero_title: 'Get recommended by\nshopping AI agents.',
    hero_desc: 'Consumers increasingly ask AI before buying. Enigma makes sure your products appear in AI-generated shopping recommendations — across every model, for every relevant query.',
    pain_points: [
      { title: 'Shopping AI is replacing search', desc: '"Best running shoes under $150" is now asked in ChatGPT as often as Google. If you\'re not cited, you\'re invisible to that buyer.' },
      { title: 'Product data isn\'t AI-ready', desc: 'AI agents struggle with JS-heavy storefronts. They need structured, token-efficient product data — which most stores don\'t serve.' },
      { title: 'No benchmark for AI visibility', desc: 'You track SEO rankings and ad performance — but you have no metrics for how often AI recommends your products.' },
    ],
    benefits: [
      { icon: '📦', title: 'AI-ready product content', desc: 'AXP serves structured product data to shopping agents — specs, reviews, comparisons — in a format they actually use.' },
      { icon: '🏆', title: 'Category ownership', desc: 'Identify which product categories are searched in AI and make sure your products dominate those answers.' },
      { icon: '⭐', title: 'Review & trust signals', desc: 'Surface the trust signals AI looks for: ratings, certifications, social proof — in a machine-readable format.' },
    ],
    quote: '"We saw AI-driven discovery grow 3x in six months after deploying Enigma. It\'s now one of our top acquisition channels."',
    quote_author: 'Maya Chen',
    quote_role: 'Head of Growth, Stripe',
    stat: '3×',
    stat_label: 'growth in AI-driven product discovery',
    cta_title: 'Make your products AI-discoverable.',
    cta_desc: 'See how Enigma works for e-commerce brands.',
  },
  agencies: {
    slug: 'solution-agencies',
    eyebrow: 'For Agencies',
    hero_title: 'Manage AI presence\nfor every client.',
    hero_desc: 'Enigma gives agencies a scalable platform to deliver GEO/AEO services — with multi-brand dashboards, white-label reporting, and reseller pricing.',
    pain_points: [
      { title: 'Clients are asking about AI SEO', desc: 'Every client wants to know: "Are we showing up in ChatGPT?" You need a platform that answers that question — and fixes it.' },
      { title: 'Manual monitoring doesn\'t scale', desc: 'Checking AI answers manually across multiple clients and models is not sustainable. You need automated tracking.' },
      { title: 'No white-label AI reporting', desc: 'Existing tools don\'t let you brand the reports or present AI visibility data under your agency identity.' },
    ],
    benefits: [
      { icon: '🗂️', title: 'Multi-brand dashboard', desc: 'Manage AI monitoring for all your clients from a single workspace with brand-level isolation.' },
      { icon: '🏷️', title: 'White-label reports', desc: 'Export branded AI presence reports with your agency logo and domain.' },
      { icon: '💼', title: 'Reseller pricing', desc: 'Generous agency margins, volume discounts, and a dedicated partner success manager.' },
    ],
    quote: '"Enigma let us launch a GEO service in 30 days. We landed three enterprise clients in the first month."',
    quote_author: 'Priya Mehta',
    quote_role: 'CEO, Loom',
    stat: '30 days',
    stat_label: 'to launch a full GEO service offering',
    cta_title: 'Launch your GEO practice.',
    cta_desc: 'Talk to our agency partnerships team.',
  },
};

export const resources = {
  'geo-playbook': {
    slug: 'resource-geo-playbook',
    eyebrow: 'GEO Playbook',
    hero_title: 'The complete guide to\nGenerative Engine Optimization.',
    hero_desc: 'Everything you need to understand, measure, and grow your brand\'s presence in AI search — from first principles to advanced tactics.',
    chapters: [
      { num: '01', title: 'What is GEO?', desc: 'Generative Engine Optimization is the practice of making your brand appear in AI-generated answers. Learn why it\'s different from SEO — and why it matters more.' },
      { num: '02', title: 'How LLMs choose what to cite', desc: 'AI models don\'t rank pages — they build answers from sources they trust. We break down the signals that make a source citation-worthy.' },
      { num: '03', title: 'Your first AI audit', desc: 'Run a structured audit of your current AI presence in 4 steps — no tools required.' },
      { num: '04', title: 'Content for AI vs. humans', desc: 'The content that earns citations is structured, factual, and token-efficient. Learn the exact format AI models prefer.' },
      { num: '05', title: 'Measuring AI presence', desc: 'Define your GEO KPIs: citation rate, share of voice, and prompt coverage. Build a dashboard you\'ll actually use.' },
      { num: '06', title: 'Advanced: AXP & agent serving', desc: 'Serve dedicated AI-optimized content at the edge. The technical playbook for teams ready to go deep.' },
    ],
    cta_title: 'Put the playbook into practice.',
    cta_desc: 'Enigma automates everything you just read.',
  },
  'research-lab': {
    slug: 'resource-research-lab',
    eyebrow: 'Research Lab',
    hero_title: 'How LLMs decide\nwhat to cite.',
    hero_desc: 'Original research from the Enigma team on how AI search systems select, cite, and rank sources — updated monthly.',
    articles: [
      { date: 'May 2026', title: 'Citation decay: why AI stops citing sources over time', desc: 'We analyzed 2.4M citations across six months and found that 34% of sources lose their citations within 90 days. Here\'s why — and how to prevent it.' },
      { date: 'Apr 2026', title: 'The token budget problem: what gets cut when context windows fill', desc: 'When a page is too long, AI models summarize. We tested which content survives summarization — and which disappears.' },
      { date: 'Mar 2026', title: 'Structured data vs. prose: which earns more citations?', desc: 'A controlled experiment with 400 content variants shows that structured fact blocks earn 2.8× more citations than equivalent prose.' },
      { date: 'Feb 2026', title: 'How Perplexity, ChatGPT, and Claude differ in source selection', desc: 'Same query. Three models. Very different citation behavior. Our analysis of 18,000 prompt runs reveals the divergence.' },
      { date: 'Jan 2026', title: 'The authority signal: how domain age affects AI citation rates', desc: 'New domains earn fewer citations regardless of content quality. We quantify the gap and show how structured signals can partially compensate.' },
      { date: 'Dec 2025', title: 'Entity disambiguation: why AI confuses brands with similar names', desc: 'When your brand name is also a common word, AI models frequently cite the wrong source. Here\'s how to establish a clear entity fingerprint.' },
    ],
    cta_title: 'Get research updates in your inbox.',
    cta_desc: 'New research drops every month.',
  },
  changelog: {
    slug: 'resource-changelog',
    eyebrow: 'Changelog',
    hero_title: 'New features,\nevery week.',
    hero_desc: 'Enigma ships fast. Here\'s everything we\'ve released — from major features to small improvements.',
    updates: [
      { date: 'May 8, 2026', tag: 'New', title: 'Gemini 2.0 monitoring support', desc: 'Monitoring & Citations now tracks brand mentions across Google\'s Gemini 2.0 model, including AI Overviews.' },
      { date: 'Apr 29, 2026', tag: 'Improved', title: 'AXP edge latency reduced to 2ms', desc: 'Agent detection and content transformation now completes in under 2ms at the edge — down from 5ms.' },
      { date: 'Apr 21, 2026', tag: 'New', title: 'White-label reports for agencies', desc: 'Agency plan users can now export fully branded AI presence reports with custom logo, domain, and color palette.' },
      { date: 'Apr 14, 2026', tag: 'New', title: 'Slack alerts for citation changes', desc: 'Get real-time Slack notifications when your brand presence drops or a competitor gains ground.' },
      { date: 'Apr 7, 2026', tag: 'Improved', title: 'Insights: action scoring v2', desc: 'Our action scoring algorithm now weighs expected citation lift against content effort — giving better recommendations.' },
      { date: 'Mar 28, 2026', tag: 'New', title: 'Site Maps: token heatmaps', desc: 'Visualize exactly which parts of each page make it into an AI\'s context window — and which get truncated.' },
    ],
    cta_title: 'Stay on the cutting edge of AI search.',
    cta_desc: 'Follow us for real-time updates.',
  },
};

export const pricing = {
  slug: 'pricing',
  hero_title: 'Simple, transparent pricing.',
  hero_desc: 'Start free. Scale as your AI presence grows.',
  plans: [
    {
      name: 'Starter',
      price_monthly: 0,
      price_annual: 0,
      desc: 'For individuals and small teams exploring AI visibility.',
      cta: 'Get started free',
      cta_style: 'outline',
      features: [
        '5 monitored prompts',
        '2 AI models (ChatGPT, Perplexity)',
        'Weekly presence report',
        'Basic citation tracking',
        '1 user seat',
        'Community support',
      ],
    },
    {
      name: 'Growth',
      price_monthly: 299,
      price_annual: 249,
      desc: 'For growing teams that need serious AI visibility.',
      cta: 'Start free trial',
      cta_style: 'cobalt',
      highlight: true,
      features: [
        '500 monitored prompts',
        'All 4 major AI models',
        'Daily presence updates',
        'Full citation tracking',
        'AXP agent serving',
        'Competitive benchmarking',
        'Slack & email alerts',
        '5 user seats',
        'Priority support',
      ],
    },
    {
      name: 'Enterprise',
      price_monthly: null,
      price_annual: null,
      desc: 'For large organizations with advanced needs.',
      cta: 'Book a demo',
      cta_style: 'dark',
      features: [
        'Unlimited prompts',
        'All AI models + custom',
        'Real-time monitoring',
        'White-label reports',
        'Forward-deployed engineers',
        'SSO & SAML',
        'SOC 2 Type II',
        'Data residency (US/EU)',
        'Unlimited seats',
        'Dedicated CSM',
      ],
    },
  ],
  faqs: [
    { q: 'What counts as a "monitored prompt"?', a: 'A monitored prompt is a query we run across AI models on your behalf — e.g. "best project management tool for remote teams". We run each prompt daily across the models in your plan.' },
    { q: 'Can I change plans later?', a: 'Yes. You can upgrade or downgrade at any time. Upgrades take effect immediately; downgrades apply at your next billing cycle.' },
    { q: 'What AI models are included?', a: 'Growth plans include ChatGPT (GPT-4o), Perplexity, Claude, and Gemini. Enterprise plans can add custom or emerging models on request.' },
    { q: 'Is there a free trial for Growth?', a: 'Yes — all Growth plans include a 14-day free trial, no credit card required.' },
    { q: 'How does AXP work technically?', a: 'AXP runs at the CDN/edge layer. We provide a Cloudflare Worker, Vercel Edge Function, or reverse proxy config. No changes to your codebase are needed.' },
    { q: 'Do you support multiple brands or clients?', a: 'Yes — the Agency plan supports multi-brand workspaces with role-based access, white-label reports, and per-client billing. Contact us for volume pricing.' },
    { q: 'How is Enigma different from traditional SEO tools?', a: 'Traditional SEO tools track rankings in Google. Enigma tracks citations in AI-generated answers — a fundamentally different signal. We also actively improve your AI presence via AXP, not just measure it.' },
  ],
};
