// Static fallback content — override via Directus (slug = key name)

export const products = {
  axp: {
    slug: 'product-axp',
    eyebrow: 'Agent Experience Platform',
    hero_title: 'Serve every AI agent\nthe perfect content.',
    hero_desc: 'AXP detects AI crawlers at the network edge and delivers token-efficient, structured responses — without changing a single line of your codebase.',
    badge: '−98.99% token reduction',
    steps: [
      { num: '01', title: 'Agent detected at edge', desc: 'ChatGPT, Perplexity, Claude, Bing AI and 60+ other agents are identified in <5ms.' },
      { num: '02', title: 'Content transformed', desc: 'AXP strips JS, nav, and decorative HTML — serving clean, structured facts.' },
      { num: '03', title: 'Human view preserved', desc: 'Your visitors get the full experience. Agents get their own optimized version.' },
      { num: '04', title: 'Citations tracked', desc: 'Every agent visit is logged. See which pages earn citations and which get ignored.' },
    ],
    features: [
      { icon: '⚡', title: 'Edge detection', desc: 'Identify 60+ AI agents at the CDN level with zero app-layer overhead.' },
      { icon: '🗜', title: 'Token compression', desc: 'Reduce page weight 90–99% for LLMs. More context, fewer tokens spent.' },
      { icon: '📄', title: 'Structured content', desc: 'Auto-generate semantic HTML, JSON-LD, and citation-ready fact blocks.' },
      { icon: '🔬', title: 'Agent A/B testing', desc: 'Serve multiple content variants to different agents and measure citation lift.' },
      { icon: '📡', title: 'Live agent logs', desc: 'Real-time feed of every agent crawl with user-agent, content served, and response time.' },
      { icon: '💾', title: 'Smart caching', desc: 'Agent-optimized content is cached separately. Zero latency for returning crawlers.' },
    ],
    stats: [{ value: '60+', label: 'AI agents detected' }, { value: '<5ms', label: 'Detection overhead' }, { value: '99%', label: 'Token reduction' }],
    cta_title: 'Ready to serve AI agents perfectly?',
    cta_desc: 'Deploy AXP in minutes — no code changes needed.',
  },
  'agent-traffic': {
    slug: 'product-agent-traffic',
    eyebrow: 'Agent Traffic',
    hero_title: 'See every AI bot\nthat visits your site.',
    hero_desc: 'Agent Traffic reveals which AI systems are crawling your pages, how often, and what content they consume — giving you complete visibility into your AI audience.',
    badge: '1.8M+ agent visits tracked weekly',
    steps: [
      { num: '01', title: 'Passive monitoring', desc: 'No SDK, no script tags. Agent Traffic reads your server logs or CDN events.' },
      { num: '02', title: 'Agent fingerprinting', desc: 'Each visit is matched against our database of 60+ known AI crawlers.' },
      { num: '03', title: 'Content mapping', desc: 'See which pages, sections, and structured data get consumed.' },
      { num: '04', title: 'Trend alerts', desc: 'Get notified when a new AI system starts crawling or traffic spikes unexpectedly.' },
    ],
    features: [
      { icon: '📊', title: 'Real-time dashboard', desc: 'Live feed of agent visits — model, page, timestamp, content consumed.' },
      { icon: '📈', title: 'Historical trends', desc: 'Track how AI traffic to your site evolves week over week.' },
      { icon: '🔍', title: 'Page-level insights', desc: 'Discover which pages attract the most AI attention and why.' },
      { icon: '🔔', title: 'Anomaly detection', desc: 'Automatic alerts for unusual crawl patterns or new agent types.' },
      { icon: '🏁', title: 'Competitor comparison', desc: 'Benchmark your AI traffic vs. similar sites in your category.' },
      { icon: '🔗', title: 'Export & API', desc: 'Push agent traffic data into your data warehouse or BI tools.' },
    ],
    stats: [{ value: '1.8M+', label: 'Agent visits weekly' }, { value: '60+', label: 'Agent types identified' }, { value: 'Real-time', label: 'Data latency' }],
    cta_title: 'Know exactly who\'s crawling you.',
    cta_desc: 'Connect in minutes via log forwarding or our CDN plugin.',
  },
  'site-maps': {
    slug: 'product-site-maps',
    eyebrow: 'Site Maps',
    hero_title: 'Map exactly how\nAI consumes your site.',
    hero_desc: 'Site Maps renders your site through the eyes of every major AI model — showing which pages get read, which get skipped, and what content ends up in context windows.',
    badge: 'Full crawl simulation in 30s',
    steps: [
      { num: '01', title: 'Crawl simulation', desc: 'We simulate how GPT, Claude, Perplexity and others actually process your pages.' },
      { num: '02', title: 'Content visibility score', desc: 'Every page gets scored: how much of it reaches an AI context window?' },
      { num: '03', title: 'Gap identification', desc: 'Find pages that are technically crawlable but effectively invisible to AI.' },
      { num: '04', title: 'Fix recommendations', desc: 'Actionable fixes: semantic structure, token density, internal linking.' },
    ],
    features: [
      { icon: '🗺️', title: 'Visual site map', desc: 'Interactive map of your entire site from the AI perspective.' },
      { icon: '👁️', title: 'Content visibility scores', desc: 'Page-by-page scoring of AI readability and context coverage.' },
      { icon: '🌡️', title: 'Token heatmaps', desc: 'See which parts of each page make it into an AI\'s context window.' },
      { icon: '🔀', title: 'Crawl path analysis', desc: 'Understand the order in which agents process your site structure.' },
      { icon: '🧩', title: 'Schema coverage', desc: 'Audit structured data coverage across your entire site.' },
      { icon: '🏆', title: 'Competitor crawl maps', desc: 'Compare how AI processes your site vs. top competitors.' },
    ],
    stats: [{ value: '30s', label: 'Full crawl simulation' }, { value: '100%', label: 'Page coverage' }, { value: '6', label: 'Models simulated' }],
    cta_title: 'See your site the way AI does.',
    cta_desc: 'Run your first crawl simulation free — no credit card needed.',
  },
  monitoring: {
    slug: 'product-monitoring',
    eyebrow: 'Monitoring & Citations',
    hero_title: 'Know exactly when\nAI mentions you.',
    hero_desc: 'Monitor thousands of prompts across ChatGPT, Perplexity, Claude, and Gemini — and get alerted the moment your brand appears, disappears, or gets outranked.',
    badge: '8M+ citations tracked weekly',
    steps: [
      { num: '01', title: 'Set up prompts', desc: 'Define the queries that matter to your buyers. We run them across all major AI models.' },
      { num: '02', title: 'Track responses', desc: 'Every AI answer is captured, parsed, and analyzed for brand mentions and citations.' },
      { num: '03', title: 'Competitive benchmarking', desc: 'See how your presence compares to competitors for each prompt category.' },
      { num: '04', title: 'Alert & optimize', desc: 'Get notified of drops. Our recommendations show you what to fix.' },
    ],
    features: [
      { icon: '🤖', title: 'Multi-model monitoring', desc: 'Track mentions across ChatGPT, Perplexity, Claude, Gemini, Bing AI and more.' },
      { icon: '🔖', title: 'Citation tracking', desc: 'See exactly which sources AI cites when it mentions your category.' },
      { icon: '💬', title: 'Sentiment analysis', desc: 'Understand how AI describes your brand — positive, neutral, or negative.' },
      { icon: '🎯', title: 'Competitive intelligence', desc: 'Know which competitors are mentioned more often and why.' },
      { icon: '📈', title: 'Historical trends', desc: 'Track your AI presence over time and measure the impact of content changes.' },
      { icon: '🔔', title: 'Custom alerts', desc: 'Slack and email alerts when your brand presence drops or spikes.' },
    ],
    stats: [{ value: '8M+', label: 'Citations tracked weekly' }, { value: '4', label: 'Major AI models' }, { value: 'Daily', label: 'Prompt refresh rate' }],
    cta_title: 'Never miss an AI mention again.',
    cta_desc: 'Start monitoring your brand across all AI search engines today.',
  },
  insights: {
    slug: 'product-insights',
    eyebrow: 'Insights',
    hero_title: 'Turn AI data\ninto growth actions.',
    hero_desc: 'Insights synthesizes your monitoring data, citation patterns, and competitive landscape into a prioritized action plan — so your team always knows what to do next.',
    badge: 'Prioritized recommendations weekly',
    steps: [
      { num: '01', title: 'Data aggregation', desc: 'All your AXP, monitoring, and traffic data is synthesized automatically.' },
      { num: '02', title: 'Gap analysis', desc: 'Our AI identifies where you\'re underperforming vs. your potential.' },
      { num: '03', title: 'Action scoring', desc: 'Every recommendation is scored by expected citation lift and effort required.' },
      { num: '04', title: 'Progress tracking', desc: 'Measure how each action improves your AI presence over time.' },
    ],
    features: [
      { icon: '📰', title: 'Weekly AI briefing', desc: 'Automated digest of your AI presence, wins, and opportunities.' },
      { icon: '🔍', title: 'Content gap finder', desc: 'Discover topics where you\'re missing from AI answers entirely.' },
      { icon: '⚡', title: 'Quick wins queue', desc: 'Low-effort, high-impact actions ranked by expected citation lift.' },
      { icon: '💰', title: 'ROI dashboard', desc: 'Track how AI visibility translates to pipeline and revenue.' },
      { icon: '👥', title: 'Team collaboration', desc: 'Assign actions, set owners, and track completion across your team.' },
      { icon: '🔌', title: 'Integrations', desc: 'Push insights into Notion, Linear, Jira, or your CMS.' },
    ],
    stats: [{ value: 'Weekly', label: 'Action briefings' }, { value: '3×', label: 'Avg. citation lift' }, { value: '90 days', label: 'Avg. to first results' }],
    cta_title: 'Start acting on AI data.',
    cta_desc: 'Insights is included in all Enigma plans.',
  },
};

export const solutions = {
  'b2b-saas': {
    slug: 'solution-b2b-saas',
    eyebrow: 'For B2B SaaS',
    hero_title: 'Win deals decided\nin AI conversations.',
    hero_desc: 'B2B buyers now ask AI before they ask Google. Enigma makes sure your SaaS product is the one that gets recommended — for every relevant use case, across every AI model.',
    pain_points: [
      { title: 'Buyers research in AI', desc: '"What\'s the best CRM for a 50-person sales team?" — If you\'re not the answer, you lose the deal before your SDR even reaches out.' },
      { title: 'Competitors are already there', desc: 'While you optimize for Google, your competitors are investing in AI presence. The window to move first is closing.' },
      { title: 'No visibility into AI traffic', desc: 'You can\'t see which AI systems visit your site, what they consume, or whether your content earns citations.' },
    ],
    benefits: [
      { icon: '🎯', title: 'Own high-intent AI queries', desc: 'Identify the prompts your ideal buyers ask AI and engineer your site to be the cited answer.' },
      { icon: '🔍', title: 'Track competitor mentions', desc: 'Know every time a competitor gets recommended instead of you — and see exactly why.' },
      { icon: '⚡', title: 'Serve AI the facts it needs', desc: 'AXP serves structured, token-efficient content to AI crawlers. More citations, fewer tokens wasted.' },
    ],
    quote: '"More of our pipeline now comes from AI-influenced research than Google. Enigma was the fastest way to own that channel."',
    quote_author: 'Jordan Duarte',
    quote_role: 'Sr. Director of Web Strategy, Stratamesh',
    stat: '412%',
    stat_label: 'increase in brand presence for non-branded prompts',
    cta_title: 'Win the AI search channel.',
    cta_desc: 'Book a demo to see how Enigma works for B2B SaaS.',
  },
  ecommerce: {
    slug: 'solution-ecommerce',
    eyebrow: 'For E-commerce',
    hero_title: 'Get recommended by\nshopping AI agents.',
    hero_desc: 'Consumers increasingly ask AI before buying. Enigma makes sure your products appear in AI-generated shopping recommendations — across every model, for every relevant query.',
    pain_points: [
      { title: 'Shopping AI is replacing search', desc: '"Best running shoes under $150" is now asked in ChatGPT as often as Google. If you\'re not cited, you\'re invisible to that buyer.' },
      { title: 'Product data isn\'t AI-ready', desc: 'AI agents struggle with JS-heavy storefronts. They need structured, token-efficient product data — which most stores don\'t serve.' },
      { title: 'No benchmark for AI visibility', desc: 'You track SEO rankings and ad performance — but you have no metrics for how often AI recommends your products.' },
    ],
    benefits: [
      { icon: '📦', title: 'AI-ready product content', desc: 'AXP serves structured product data to shopping agents — specs, reviews, comparisons — in a format they actually use.' },
      { icon: '🏆', title: 'Category ownership', desc: 'Identify which product categories are searched in AI and make sure your products dominate those answers.' },
      { icon: '⭐', title: 'Review & trust signals', desc: 'Surface the trust signals AI looks for: ratings, certifications, social proof — in a machine-readable format.' },
    ],
    quote: '"We saw AI-driven discovery grow 3x in six months after deploying Enigma. It\'s now one of our top acquisition channels."',
    quote_author: 'Maya Chen',
    quote_role: 'Head of Growth, Nordique Commerce',
    stat: '3×',
    stat_label: 'growth in AI-driven product discovery',
    cta_title: 'Make your products AI-discoverable.',
    cta_desc: 'See how Enigma works for e-commerce brands.',
  },
  agencies: {
    slug: 'solution-agencies',
    eyebrow: 'For Agencies',
    hero_title: 'Manage AI presence\nfor every client.',
    hero_desc: 'Enigma gives agencies a scalable platform to deliver GEO/AEO services — with multi-brand dashboards, white-label reporting, and reseller pricing.',
    pain_points: [
      { title: 'Clients are asking about AI SEO', desc: 'Every client wants to know: "Are we showing up in ChatGPT?" You need a platform that answers that question — and fixes it.' },
      { title: 'Manual monitoring doesn\'t scale', desc: 'Checking AI answers manually across multiple clients and models is not sustainable. You need automated tracking.' },
      { title: 'No white-label AI reporting', desc: 'Existing tools don\'t let you brand the reports or present AI visibility data under your agency identity.' },
    ],
    benefits: [
      { icon: '🗂️', title: 'Multi-brand dashboard', desc: 'Manage AI monitoring for all your clients from a single workspace with brand-level isolation.' },
      { icon: '🏷️', title: 'White-label reports', desc: 'Export branded AI presence reports with your agency logo and domain.' },
      { icon: '💼', title: 'Reseller pricing', desc: 'Generous agency margins, volume discounts, and a dedicated partner success manager.' },
    ],
    quote: '"Enigma let us launch a GEO service in 30 days. We landed three enterprise clients in the first month."',
    quote_author: 'Priya Mehta',
    quote_role: 'CEO, Meridian Digital',
    stat: '30 days',
    stat_label: 'to launch a full GEO service offering',
    cta_title: 'Launch your GEO practice.',
    cta_desc: 'Talk to our agency partnerships team.',
  },
};

export const resources = {
  'geo-playbook': {
    slug: 'resource-geo-playbook',
    eyebrow: 'GEO Playbook',
    hero_title: 'The complete guide to\nGenerative Engine Optimization.',
    hero_desc: 'Everything you need to understand, measure, and grow your brand\'s presence in AI search — from first principles to advanced tactics.',
    chapters: [
      { num: '01', title: 'What is GEO?', desc: 'Generative Engine Optimization is the practice of making your brand appear in AI-generated answers. Learn why it\'s different from SEO — and why it matters more.' },
      { num: '02', title: 'How LLMs choose what to cite', desc: 'AI models don\'t rank pages — they build answers from sources they trust. We break down the signals that make a source citation-worthy.' },
      { num: '03', title: 'Your first AI audit', desc: 'Run a structured audit of your current AI presence in 4 steps — no tools required.' },
      { num: '04', title: 'Content for AI vs. humans', desc: 'The content that earns citations is structured, factual, and token-efficient. Learn the exact format AI models prefer.' },
      { num: '05', title: 'Measuring AI presence', desc: 'Define your GEO KPIs: citation rate, share of voice, and prompt coverage. Build a dashboard you\'ll actually use.' },
      { num: '06', title: 'Advanced: AXP & agent serving', desc: 'Serve dedicated AI-optimized content at the edge. The technical playbook for teams ready to go deep.' },
    ],
    cta_title: 'Put the playbook into practice.',
    cta_desc: 'Enigma automates everything you just read.',
  },
  'research-lab': {
    slug: 'resource-research-lab',
    eyebrow: 'Research Lab',
    hero_title: 'How LLMs decide\nwhat to cite.',
    hero_desc: 'Original research from the Enigma team on how AI search systems select, cite, and rank sources — updated monthly.',
    articles: [
      { date: 'May 2026', title: 'Citation decay: why AI stops citing sources over time', desc: 'We analyzed 2.4M citations across six months and found that 34% of sources lose their citations within 90 days. Here\'s why — and how to prevent it.' },
      { date: 'Apr 2026', title: 'The token budget problem: what gets cut when context windows fill', desc: 'When a page is too long, AI models summarize. We tested which content survives summarization — and which disappears.' },
      { date: 'Mar 2026', title: 'Structured data vs. prose: which earns more citations?', desc: 'A controlled experiment with 400 content variants shows that structured fact blocks earn 2.8× more citations than equivalent prose.' },
      { date: 'Feb 2026', title: 'How Perplexity, ChatGPT, and Claude differ in source selection', desc: 'Same query. Three models. Very different citation behavior. Our analysis of 18,000 prompt runs reveals the divergence.' },
    ],
    cta_title: 'Get research updates in your inbox.',
    cta_desc: 'New research drops every month.',
  },
  changelog: {
    slug: 'resource-changelog',
    eyebrow: 'Changelog',
    hero_title: 'New features,\nevery week.',
    hero_desc: 'Enigma ships fast. Here\'s everything we\'ve released — from major features to small improvements.',
    updates: [
      { date: 'May 8, 2026', tag: 'New', title: 'Gemini 2.0 monitoring support', desc: 'Monitoring & Citations now tracks brand mentions across Google\'s Gemini 2.0 model, including AI Overviews.' },
      { date: 'Apr 29, 2026', tag: 'Improved', title: 'AXP edge latency reduced to 2ms', desc: 'Agent detection and content transformation now completes in under 2ms at the edge — down from 5ms.' },
      { date: 'Apr 21, 2026', tag: 'New', title: 'White-label reports for agencies', desc: 'Agency plan users can now export fully branded AI presence reports with custom logo, domain, and color palette.' },
      { date: 'Apr 14, 2026', tag: 'New', title: 'Slack alerts for citation changes', desc: 'Get real-time Slack notifications when your brand presence drops or a competitor gains ground.' },
      { date: 'Apr 7, 2026', tag: 'Improved', title: 'Insights: action scoring v2', desc: 'Our action scoring algorithm now weighs expected citation lift against content effort — giving better recommendations.' },
      { date: 'Mar 28, 2026', tag: 'New', title: 'Site Maps: token heatmaps', desc: 'Visualize exactly which parts of each page make it into an AI\'s context window — and which get truncated.' },
    ],
    cta_title: 'Stay on the cutting edge of AI search.',
    cta_desc: 'Follow us for real-time updates.',
  },
};

export const pricing = {
  slug: 'pricing',
  hero_title: 'Simple, transparent pricing.',
  hero_desc: 'Start free. Scale as your AI presence grows.',
  plans: [
    {
      name: 'Starter',
      price_monthly: 0,
      price_annual: 0,
      desc: 'For individuals and small teams exploring AI visibility.',
      cta: 'Get started free',
      cta_style: 'outline',
      features: [
        '5 monitored prompts',
        '2 AI models (ChatGPT, Perplexity)',
        'Weekly presence report',
        'Basic citation tracking',
        '1 user seat',
        'Community support',
      ],
    },
    {
      name: 'Growth',
      price_monthly: 299,
      price_annual: 249,
      desc: 'For growing teams that need serious AI visibility.',
      cta: 'Start free trial',
      cta_style: 'cobalt',
      highlight: true,
      features: [
        '500 monitored prompts',
        'All 4 major AI models',
        'Daily presence updates',
        'Full citation tracking',
        'AXP agent serving',
        'Competitive benchmarking',
        'Slack & email alerts',
        '5 user seats',
        'Priority support',
      ],
    },
    {
      name: 'Enterprise',
      price_monthly: null,
      price_annual: null,
      desc: 'For large organizations with advanced needs.',
      cta: 'Book a demo',
      cta_style: 'dark',
      features: [
        'Unlimited prompts',
        'All AI models + custom',
        'Real-time monitoring',
        'White-label reports',
        'Forward-deployed engineers',
        'SSO & SAML',
        'SOC 2 Type II',
        'Data residency (US/EU)',
        'Unlimited seats',
        'Dedicated CSM',
      ],
    },
  ],
  faqs: [
    { q: 'What counts as a "monitored prompt"?', a: 'A monitored prompt is a query we run across AI models on your behalf — e.g. "best project management tool for remote teams". We run each prompt daily across the models in your plan.' },
    { q: 'Can I change plans later?', a: 'Yes. You can upgrade or downgrade at any time. Upgrades take effect immediately; downgrades apply at your next billing cycle.' },
    { q: 'What AI models are included?', a: 'Growth plans include ChatGPT (GPT-4o), Perplexity, Claude, and Gemini. Enterprise plans can add custom or emerging models on request.' },
    { q: 'Is there a free trial for Growth?', a: 'Yes — all Growth plans include a 14-day free trial, no credit card required.' },
    { q: 'How does AXP work technically?', a: 'AXP runs at the CDN/edge layer. We provide a Cloudflare Worker, Vercel Edge Function, or reverse proxy config. No changes to your codebase are needed.' },
  ],
};
